# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4b5ba0c17e69092123a393262b4547e86c5e597a74ad5f0d284f28522f44799e3194af57fe7b16aee8d960a844b235136e2566ed1d7b88af727ac567ca3659b

test:
  secret_key_base: 7aa6ddee10e144ac1b3e345a05a5cf25c73b2cdaf8c0cea9883e14fbd0d274d5732ddcf5b7c817cd6eaea456c7c87ba75343de7f0542e8726573599a20cfb7be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
